name: Check-Build

on: [push]

env:
  KINECTSDK10_DIR: ${{ github.workspace }}\KinectSDK-v1.8\AttachedContainer\SDK18\Microsoft SDKs\Kinect\v1.8\

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ['7.0.x' ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
          
      - name: Add MSYS64 bin to PATH
        run: echo "C:\msys64\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Install Kinect SDK18
        shell: powershell
        run: |
          New-Item -ItemType directory KinectSDK-v1.8 | Out-Null
          wget "https://download.microsoft.com/download/E/1/D/E1DEC243-0389-4A23-87BF-F47DE869FC1A/KinectSDK-v1.8-Setup.exe" -OutFile KinectSDK-v1.8-Setup.exe
          & "C:\Program Files (x86)\WiX Toolset v3.11\bin\dark.exe" KinectSDK-v1.8-Setup.exe -x KinectSDK-v1.8
          Start-Process msiexec -ArgumentList "/a ${{ github.workspace }}\KinectSDK-v1.8\AttachedContainer\KinectSDK-v1.8-x64.msi /qn TARGETDIR=${{ github.workspace }}\KinectSDK-v1.8\AttachedContainer\SDK18" -Wait -NoNewWindow
          
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Restore and build (publish)
        run: msbuild plugin_KinectV1 /restore /p:Platform=x64 /p:PlatformTarget=x64 /p:Configuration=Release /p:RuntimeIdentifier=win10-x64 /t:Publish /p:PublishProfile=plugin_KinectV1\Properties\PublishProfiles\FolderProfile.pubxml
        
      - name: Pack published files
        run: |
          cd plugin_KinectV1/bin/Release/Publish
          7z a plugin_KinectV1.zip *
        
      - name: Upload plugin artifact
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "plugin_KinectV1 Build Artifact"
          files: |
            ./plugin_KinectV1/bin/Release/Publish/plugin_KinectV1.zip
            ./external/manifest.json